#!/bin/sh

export PATH="/bin:/sbin:/usr/sbin:/usr/bin"

PREV_GW=`netstat -nr | grep '^default' | grep -v 'ppp' | sed 's/default *\([0-9\.]*\) .*/\1/'`

if [ ! -e /tmp/vpn_prev_gw ]; then
    echo "${PREV_GW}" > /tmp/vpn_prev_gw
fi

dscacheutil -flushcache
